# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-30 12:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0002_auto_20190429_0910'),
        ('users', '0003_user_email_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(auto_now_add=True)),
                ('update_time', models.DateField(auto_now=True)),
                ('title', models.CharField(max_length=10)),
                ('receiver', models.CharField(max_length=10)),
                ('detail', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=11)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('is_delete', models.BooleanField(default=False)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='areas.Area')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='areas.Area')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provinces', to='areas.Area')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-update_time'],
                'db_table': 'tb_address',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='default_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.Address'),
        ),
    ]
